language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  include:
    - php: 5.3
      dist: precise

before_install:
  - composer install -n

script:
  - ./vendor/bin/phpcs -v --standard=PSR2 src tests
  - ./vendor/bin/phpunit
