name: Tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ["5.3", "5.4", "5.6", "7.0", "7.1", "7.2", "7.3", "7.4"]

    name: Tests Under PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run Unit Tests
        run: ./vendor/bin/phpunit
